#code generated by ChatGPT
from faker import Faker
import sqlite3
import shortuuid 
import secrets

# Connect to the database file
conn = sqlite3.connect("D:\Revised IS\web\database\database3.db")

# Create a cursor object
cursor = conn.cursor()

# Create a Faker object
fake = Faker(locale='en_PH')

#Person table
#'''
# Create a list of 100 dictionaries, each dictionary representing a row in the table
data = [{
    "personID": shortuuid.uuid(),    
    "status": fake.random_element(["active", "idle", "out"]),
    "name": fake.name(),
    "email": fake.email(),
    "mobile number": fake.numerify(text='09#########'),
    "facebook link": f"https://www.facebook.com/{fake.user_name()}",
    "city": fake.city(),
    "ronin address": secrets.token_hex(20)
} for i in range(100)]

# Insert the data into the table
for row in data:
    cursor.execute("INSERT INTO Person VALUES (?,?,?,?,?,?,?,?)", list(row.values()))
    conn.commit()
#'''

#account table
'''
# Create a list of 50 dictionaries, each dictionary representing a row in the table
data = [{
    "accountID": fake.pystr(min_chars=22, max_chars=22),
    "email": fake.email(),
    "password": fake.password(),
    "ronin address": "ronin:" + fake.pystr(min_chars=40, max_chars=40).upper()
} for i in range(50)]

# Insert the data into the table
for row in data:
    cursor.execute("INSERT INTO Account VALUES (?,?,?,?)", list(row.values()))
    conn.commit()
'''

'''
#Quota table
fake_data = []
for i in range(10):
    # generate fake data using Faker
    quotaID = fake.pystr(min_chars=22, max_chars=22)
    date = "2022-12-16 07:52:25"
    fake_scholarID = 'efghijklmnopqrstuvwxyu'
    fake_accountID = 'yoUQkSFiabejaHyIFfqGEH'
    fake_SLP = fake.random_int(min=0, max=200)
    # add the fake data to the list
    fake_data.append((quotaID, date, fake_scholarID, fake_accountID, fake_SLP))

# insert the fake data into the table
cursor.executemany("INSERT INTO Quota (quotaID, date, scholarID, accountID, SLP) VALUES (?, ?, ?, ?, ?)", fake_data)

# commit the changes to the database
conn.commit()

# close the connection
conn.close()
'''

'''
#manager table
personID = 'bGtIKipdvhKbrDjdVdFiKv'
managerID = fake.pystr(min_chars=22, max_chars=22)
profit = 0
cursor.execute(f"INSERT INTO Manager (managerID, personID, profit_slp) VALUES ('{managerID}', '{personID}', '{profit}')")
conn.commit()
conn.close()
'''


